### ISSUE TITLE
V2Ray-core 版本

### ISSUE THREAD

**Issue by TomatoLeee** [eycorsican/kitsunebi-android#13]
现在客户端是要求 V2Ray-core 版本4.13。
如果我现在使用无效，是否可以断定是服务端版本太低呢？
请问是否有哪家服务商是支持这个高版本的 V2Ray-core ，可以的话麻烦告知

**Comment by qgtxqj** [comment]
似乎没要求服务端版本是4.13，除非你用QUIC。哪个服务商升级了服务端你应该去发信问客服。

**Comment by TomatoLeee** [comment]
> 似乎没要求服务端版本是4.13，除非你用QUIC。哪个服务商升级了服务端你应该去发信问客服。

谢谢您的解答，因为我上次根据给的配置改了服务的地址，用不了。不知道如何判断是服务端问题还是自己的配置错误问题？

**Comment by eycorsican** [comment]
那这就属于 v2ray-core 的问题了：https://github.com/v2ray/v2ray-core/issues
