### ISSUE TITLE
[疑问]Android版本能否像iOS版本那样在log里显示user-agent

### ISSUE THREAD

**Issue by HinderSting** [eycorsican/kitsunebi-android#131]
iOS版本的kitsunebi可以在log里显示user-agent，很容易就能把user-agent添加到规则里去，以后就可以根据user-agent来分流了，非常方便。

而且iOS上的kitsunebi甚至能看出HTTPS流量的user-agent，这是怎么做到的？(印象中这个应该是加密了的啊)
理论上，Android版本能否做出相同功能？

**Comment by redmac** [comment]
iOS版本的kitsunebi给个地址嘛

**Comment by HinderSting** [comment]
> iOS版本的kitsunebi给个地址嘛

非中国区 appstore 下载

**Comment by HinderSting** [comment]
> 而且iOS上的kitsunebi甚至能看出HTTPS流量的user-agent，这是怎么做到的？(印象中这个应该是加密了的啊)

自已看了下，iOS上可以看出user-agent是因为kitsunebi开了http-inbound,其它应用跟kitsunebi通过http 代理进行通信,这个过程可以看到user-agent。但是这个只是http 代理时的http user-agent,并不是与网站的https通信的user-agent。只是很多时候恰巧一样。网站看到的那个真正的user-agent是在加密流量里，kitsunebi也是看不到的
