### ISSUE TITLE
只得一個配置

### ISSUE THREAD

**Issue by la8896** [eycorsican/kitsunebi-android#17]
我有多個伺服器
請問能增加多项配置來配合我幾個服務器的不同協議嗎?
還有server log有很多failed
我的测試是在香港
我家安裝v2ray伺服器作測試
協議是ws+tls+nginx
下载速度也很慢
使用Bifrostv v2rayng v2rayn都不會出現這些錯誤的

2019/02/28 12:54:49 127.0.0.1:59610 accepted tcp:safebrowsing.googleapis.com:443 
2019/02/28 12:54:49 127.0.0.1:59614 accepted tcp:redirector.googlevideo.com:443 
2019/02/28 12:54:49 127.0.0.1:59612 accepted tcp:redirector.googlevideo.com:443 
2019/02/28 12:54:49 127.0.0.1:59616 accepted tcp:redirector.googlevideo.com:443 
2019/02/28 12:54:49 127.0.0.1:59613 accepted udp:172.217.160.110:443 
2019/02/28 12:54:49 127.0.0.1:59615 accepted tcp:www.speedtest.net:443 
2019/02/28 12:54:49 127.0.0.1:59611 accepted tcp:csi.gstatic.com:443 
2019/02/28 12:54:59 127.0.0.1:59626 accepted tcp:203.95.213.129:8080 
2019/02/28 12:54:59 127.0.0.1:59627 accepted tcp:203.95.213.129:8080 
2019/02/28 12:54:59 127.0.0.1:59625 accepted tcp:hk.ap.speedtest.i3d.net:80 
2019/02/28 12:54:59 127.0.0.1:59629 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:54:59 127.0.0.1:59628 accepted tcp:43.239.136.54:8080 
2019/02/28 12:54:59 127.0.0.1:59630 accepted tcp:43.239.136.54:8080 
2019/02/28 12:54:59 127.0.0.1:59631 accepted tcp:speedtesthk.gemnet.mn:80 
2019/02/28 12:54:59 127.0.0.1:59632 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:10 127.0.0.1:59642 accepted tcp:218.102.52.37:8080 
2019/02/28 12:55:10 127.0.0.1:59644 accepted tcp:www.speedtest.net:443 
2019/02/28 12:55:10 127.0.0.1:59646 accepted tcp:v.hk.vietpn.com:80 
2019/02/28 12:55:10 127.0.0.1:59647 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:10 127.0.0.1:59645 accepted tcp:218.102.52.37:8080 
2019/02/28 12:55:10 127.0.0.1:59643 accepted tcp:www.suntechspeedtest.com:80 
2019/02/28 12:55:10 127.0.0.1:59653 accepted tcp:180.149.112.98:8080 
2019/02/28 12:55:10 127.0.0.1:59655 accepted tcp:180.149.112.98:8080 
2019/02/28 12:55:10 127.0.0.1:59654 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:10 127.0.0.1:59657 accepted tcp:103.16.27.2:8080 
2019/02/28 12:55:10 127.0.0.1:59658 accepted tcp:103.16.27.2:8080 
2019/02/28 12:55:10 127.0.0.1:59659 accepted tcp:s1.hon.speedtest.interoute.net:80 
2019/02/28 12:55:10 127.0.0.1:59656 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:10 127.0.0.1:59664 accepted tcp:sb.scorecardresearch.com:443 
2019/02/28 12:55:10 127.0.0.1:59665 accepted tcp:m.optout.ziffdavis.com:443 
2019/02/28 12:55:10 127.0.0.1:59666 accepted tcp:googleads.g.doubleclick.net:443 
2019/02/28 12:55:10 127.0.0.1:59667 accepted tcp:m.optout.ziffdavis.com:443 
2019/02/28 12:55:11 127.0.0.1:59673 accepted udp:8.8.8.8:53 
2019/02/28 12:55:11 127.0.0.1:59675 accepted tcp:redirector.googlevideo.com:443 
2019/02/28 12:55:11 127.0.0.1:59674 accepted tcp:redirector.googlevideo.com:443 
2019/02/28 12:55:11 127.0.0.1:59676 accepted tcp:redirector.googlevideo.com:443 
2019/02/28 12:55:11 127.0.0.1:59680 accepted tcp:www.googletagmanager.com:443 
2019/02/28 12:55:19 127.0.0.1:59685 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:19 127.0.0.1:59684 accepted tcp:180.149.112.98:8080 
2019/02/28 12:55:20 127.0.0.1:59687 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:20 127.0.0.1:59688 accepted tcp:43.239.136.54:8080 
2019/02/28 12:55:20 127.0.0.1:59690 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:20 127.0.0.1:59691 accepted tcp:203.95.213.129:8080 
2019/02/28 12:55:20 127.0.0.1:59693 accepted udp:8.8.8.8:53 
2019/02/28 12:55:21 127.0.0.1:59695 accepted tcp:157.240.24.55:5222 
2019/02/28 12:55:21 127.0.0.1:59694 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:21 127.0.0.1:59696 accepted tcp:103.16.27.2:8080 
2019/02/28 12:55:21 127.0.0.1:59699 accepted tcp:mtalk.google.com:5228 
2019/02/28 12:55:22 127.0.0.1:59701 accepted tcp:218.102.52.37:8080 
2019/02/28 12:55:22 127.0.0.1:59702 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:22 127.0.0.1:59703 accepted tcp:218.102.52.37:8080 
2019/02/28 12:55:22 127.0.0.1:59706 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1000 (normal)
2019/02/28 12:55:22 127.0.0.1:59707 accepted udp:218.102.52.37:39764 
2019/02/28 12:55:22 127.0.0.1:59708 accepted tcp:218.102.52.37:8080 
2019/02/28 12:55:38 127.0.0.1:59713 accepted tcp:config.88-f.net:80 
2019/02/28 12:55:38 127.0.0.1:59715 accepted tcp:aax-fe-sin.amazon-adsystem.com:443 
2019/02/28 12:55:38 127.0.0.1:59716 accepted tcp:147.92.249.2:443 
2019/02/28 12:55:38 127.0.0.1:59720 accepted tcp:218.102.52.37:8080 
2019/02/28 12:55:38 127.0.0.1:59719 accepted tcp:218.102.52.37:8080 
2019/02/28 12:55:38 127.0.0.1:59718 accepted tcp:pubads.g.doubleclick.net:443 
2019/02/28 12:55:38 127.0.0.1:59717 accepted tcp:config.88-f.net:80 
2019/02/28 12:55:39 127.0.0.1:59727 accepted tcp:pagead2.googlesyndication.com:443 
2019/02/28 12:55:39 127.0.0.1:59729 accepted tcp:pagead2.googlesyndication.com:443 
2019/02/28 12:55:39 127.0.0.1:59728 accepted tcp:pagead2.googlesyndication.com:443 
2019/02/28 12:55:41 127.0.0.1:59734 accepted udp:8.8.8.8:53 
2019/02/28 12:55:42 127.0.0.1:59735 accepted tcp:googleads4.g.doubleclick.net:443 
2019/02/28 12:55:50 127.0.0.1:59740 rejected  v2ray.com/core/proxy/vmess/encoding: failed to read request header > websocket: close 1006 (abnormal closure): unexpected EOF

**Comment by emdoe** [comment]
可以在单个配置文件中直接加入多个服务器，有两种方法可以实现这种效果。旧式的方法是在 outbounds 中的代理部分的 vnext 当中，有

```JSON
"vnext": [
    { 
        // 第一个服务器的相关信息 
    },
    { 
        // 第二个服务器的相关信息
    },
    ...
    {
        // 第 k 个服务器的配置信息
    }
]
```
新式的方法则相对复杂，先不妨假设原来的 outbounds 连接服务器的部分 tag 为 proxy，则现在可将不同的服务器标注为不同的 tag，例如：

```JSON
"outbounds": [
    {
        "tag": "London",
        "settings": {
            ...
        },
        ...
    },
    {
        "tag": "Chicago",
        ...
     },
     ...
]

```

再在 routing 部分，修改为

```JSON
"routing": {
    "balancers": [
        {
            "tag": "proxy",
            "selector": [
                "London",
                "Chicago",
                ...
            ]
        }
    ],
    ...
}

```

**Comment by eycorsican** [comment]
不放配置只给错误日志你就是白搭

**Comment by la8896** [comment]
不好意思,可能我表達不太好,我的意思是能否獨立選擇使用某一個伺服器,就好像其它如ng或bv這種型式

**Comment by emdoe** [comment]
唔…我猜目前来说可能不太行？一种替代的方法是你在 selector 中仅设置一个，在需要切换的时候修改为新的那一个的 tag，这样不知能否暂时解决你的问题呢？

**Comment by sato84** [comment]
希望能够追加像ss, ssr一样可以选择配置文件的功能。
