### ISSUE TITLE
連接速度很慢

### ISSUE THREAD

**Issue by la8896** [eycorsican/kitsunebi-android#21]
### 你正在使用哪个版本？
最新版本

### 使用最新版本是否还遇到同样的问题？
連接速度很慢

### 你的手机型号和手机操作系统版本是多少？
三星Note 8,華為Mate 10

各方面都很大改進，但始終開啓連綫速度很慢，點了play後需要十多秒才能連接(比ng或bv),希望下一版本有改進。

**Comment by eycorsican** [comment]
你指网络连接慢还是启动慢？

**Comment by la8896** [comment]
現在正常了
Thx

eycorsican <notifications@github.com> 於 2019年3月25日 週一 下午4:16寫道：

**Comment by la8896** [comment]
我在香港測試的，v2ray server安裝在家裡Asus RT-AC86U裡,在家裡用手機wifi進行測試的 按了play後需要八至十二秒才能打開youtube網頁,用BV或NG只需要兩至三秒就能打開youtube網頁

**Comment by sbily1988** [comment]
这个我也有同感，kitsunebi启动后，点击右下角的那个小三角按钮，VPN小钥匙出现了大约10s到20s才可以正常的使用

**Comment by sbily1988** [comment]
网络连接慢

**Comment by windy1lee** [comment]
一段时间（大约5分钟）未使用需要代理的app，再使用的时候，连接很慢，大约10秒才会有反应

**Comment by la8896** [comment]
剛更新到1.1.7版本后，真的快了很多，謝謝您

**Comment by la8896** [comment]
剛更新了,連线速度又變得很慢

**Comment by windy1lee** [comment]
最新版本（1.3.2）也感觉出现如下问题，感觉问题在上一版本中没有1.3.2这么严重：

1、点击右下角的那个小三角按钮，VPN小钥匙出现了大约10s到20s才可以正常的使用

2、一段时间（大约5分钟）未使用需要代理的app，再使用的时候，连接很慢，大约10秒才会有反应

**Comment by eycorsican** [comment]
#39

**Comment by la8896** [comment]
Hello there,

I just signed the petition "Request Permanent Court of Arbitration
to Investigate Unlawful Use of Force of Hong Kong Police" and wanted to see
if you could help by adding your name.

Our goal is to reach 1,000,000 signatures and we need more support. You can
read more and sign the petition here:

http://chng.it/MWnfMHLKFH

Thanks!
S

**Comment by sbily1988** [comment]
No thanks, I'm not interested in politics，Please do not sign for me
sbily1988

LA <notifications@github.com> 于 2019年12月16日周一 21:32写道：
