### ISSUE TITLE
使用TCP类型无法伪装HTTP

### ISSUE THREAD

**Issue by odesky** [eycorsican/kitsunebi-android#22]
### 你正在使用哪个版本？
Google Play 1.1.7

### 使用最新版本是否还遇到同样的问题？
是

### 你的手机型号和手机操作系统版本是多少？
MEIZU MX5 
Android 5.1

### 你遇到了什么问题？
使用V2ray 的TCP模式中设置了伪装HTTP,因为APP里没办法设置.引至无法连接/

### 你遇到的问题可以用固定步骤重现吗？
是.

### 你正使用的配置
```json

<!-- 请把你的配置文件复制至此 (建议把服务器和用户信息去掉) -->

```

**Comment by odesky** [comment]
Kitsunebi 安卓版本.使用TCP类型启用HTTP伪装.因为APP里没有办法设置.引至无法连接.
v2Ray的TCP是可以使用偽裝的。但服務器設置了偽裝後，客戶端沒有地方設置。所以就聯不上了。
用kitsunebi只能把配置成為
TCP+none
並不能設置為TCP+HTTP。

**Comment by eycorsican** [comment]
后面应该会加上

**Comment by odesky** [comment]
非常感謝您的留意.
謝謝.
