### ISSUE TITLE
规则集里的FINAL,PROXY不起作用啊

### ISSUE THREAD

**Issue by qgtxqj** [eycorsican/kitsunebi-android#23]
### 你正在使用哪个版本？
1.1.7

### 使用最新版本是否还遇到同样的问题？
是

### 你的手机型号和手机操作系统版本是多少？
s9+ android 9.0

### 你遇到了什么问题？
规则集里你FINAL,PROXY在运行中配置里看不到啊。也不起作用。

### 你正使用的配置
```json

<!-- 请把你的配置文件复制至此 (建议把服务器和用户信息去掉) -->

```

**Comment by eycorsican** [comment]
你根据什么来判断没生效？

**Comment by qgtxqj** [comment]
不好意思，没注意看whatismyip.com在direct里面。
