### ISSUE TITLE
规则集中部分PROXY项生成的配置文件是BLOCK

### ISSUE THREAD

**Issue by qgtxqj** [eycorsican/kitsunebi-android#26]
### 你正在使用哪个版本？
1.2.4

### 使用最新版本是否还遇到同样的问题？
1.2.3无此问题

### 你遇到了什么问题？
https://raw.githubusercontent.com/ConnersHua/Profiles/master/Kitsunebi/Pro.conf
787行开始的项是PROXY，结果google在运行日志中被block，查看配置文件确实是block了。1.2.4独有问题。

### 你正使用的配置
```json

<!-- 请把你的配置文件复制至此 (建议把服务器和用户信息去掉) -->

```

**Comment by qgtxqj** [comment]
重置规则集后也有这个问题
   "rules": [
      {
        "domain": [
          "geosite:category-ads-all",
          "domain:doubleclick.net",
          "domain:setup.icloud.com",  //默认PROXY项
          "domain:services.googleapis.cn" //这项是我自己添加在规则集的PROXY
        ],
        "outboundTag": "block",
        "type": "field"
      },

**Comment by eycorsican** [comment]
1.2.6 中应该修好了

**Comment by qgtxqj** [comment]
好了。
