### ISSUE TITLE
bug反馈

### ISSUE THREAD

**Issue by windy1lee** [eycorsican/kitsunebi-android#32]
1。v2ray订阅功能无法正常使用
点击刷新显示更新时间，但节点未导入。
2。测速功能，启动代理再关闭，再测速都是timeout。需要彻底退出重新进入APP才能测速。

**Comment by windy1lee** [comment]
机场为喵帕斯，
v2rayN，v2rayng，bifrostv均可订阅导入，
在使用1.3.2订阅功能时出现：
failed to decode
v2rayN vmess URL V2

是因为不支持该格式的订阅吗？？

**Comment by eycorsican** [comment]
你发完整的错误信息

**Comment by windy1lee** [comment]
不会操作！！！！

**Comment by eycorsican** [comment]
就把弹出错误信息的界面截个图来。

其实最好是把URI发给我重现问题。

**Comment by windy1lee** [comment]
推特私信给你，请查收！

**Comment by eycorsican** [comment]
会在下个版本做兼容。

这个问题基本上是机场没把 URI 写对导致的，按 [这个页面](https://github.com/2dust/v2rayN/wiki/%E5%88%86%E4%BA%AB%E9%93%BE%E6%8E%A5%E6%A0%BC%E5%BC%8F%E8%AF%B4%E6%98%8E(ver-2)) 的示例，所有字段都是 `string`，但你这个机场把 `aid` 字段写成 `int` 了。

**Comment by windy1lee** [comment]
好的，感谢！！
