### ISSUE TITLE
希望保留/增加“通过纯文本方式修改配置”的选项

### ISSUE THREAD

**Issue by llpub** [eycorsican/kitsunebi-android#33]
通过gui设置对于普通用户比较友好，但是需要深度自定义配置的话有点不够用（比如修改dns的端口gui好像就做不到）
希望能保留（增加？听说以前的版本有这个东西）“通过纯文本方式修改配置”。
比如，在kitsunebi的规则集里就可以很容易的自行做成gfwlist模式，就是得益于这个规则集是纯文本方式配置的。
见识比较浅，希望大家讨论讨论，可行的话再麻烦大神考虑一下，谢谢

**Comment by eycorsican** [comment]
从 “运行配置” 中复制，再到 ”添加配置“ 中从粘贴板添加，再自行修改。
