### ISSUE TITLE
建议：分应用代理那里能否增加搜索 以及路由模式（绕过局域网及大陆地址）

### ISSUE THREAD

**Issue by 06ji** [eycorsican/kitsunebi-android#36]
### 你正使用的配置
```json

<!-- 请把你的配置文件复制至此 (建议把服务器和用户信息去掉) -->

```

建议：分应用代理那里能否增加 搜索（因为一个一个找好麻烦）以及路由模式（绕过局域网及大陆地址）
还有能不能支持ssr订阅？

**Comment by eycorsican** [comment]
> 分应用代理那里能否增加 搜索
#69 

> 还有能不能支持ssr订阅？
除非 V2Ray 支持
