### ISSUE TITLE
不支援233一鍵脚本

### ISSUE THREAD

**Issue by la88962** [eycorsican/kitsunebi-android#40]
用qr code或手動配置和導入配置都是無法連线
Server 是TLS +h2的

**Comment by windy1lee** [comment]
节点信息导入目前应该是没问题。你说的不支持，看看设置是否正确吧

**Comment by la88962** [comment]
您好,剛剛更新了也不能連線成功,但用ng或bv可正常連接

**Comment by eycorsican** [comment]
简单看了下你所说的一键脚本说明，没找到相关实现标准的说明，你得提供更加详细的信息。

**Comment by la88962** [comment]
233一健的传输协议是HTTP/2

**Comment by la88962** [comment]
剛剛更新了最新版本,233一键還是不能上網

**Comment by llpub** [comment]
233一鍵脚本里有个命令:`v2ray url`生成的vmess格式链接可以导入kilsunebi，测试过可用。

**Comment by la88962** [comment]
剛剛再測試了,確實現在可用,谢谢您
