### ISSUE TITLE
订阅填错位置

### ISSUE THREAD

**Issue by wjyjwy** [eycorsican/kitsunebi-android#41]
### 你正在使用哪个版本？
1.4.1

### 你遇到了什么问题？
订阅的时候填错位置了。把host的内容填到path里去了。用v2rayng订阅没问题。

以下是订阅内容解码后，其中一条vmess再解码的内容，其中ID内容被我改掉隐藏了

{"add":"plus.jiyou.fun","host":"box.10155.com","id":"我把ID内容改掉隐藏了","net":"ws","path":"","port":"8080","ps":"\u65e5\u672c(1.0)","tls":"","v":2,"aid":0,"type":"none"}

### 你遇到的问题可以用固定步骤重现吗？
可以

https://home.jiyou.fun/ 这个网站的订阅会出问题
### 你正使用的配置
```json

<!-- 请把你的配置文件复制至此 (建议把服务器和用户信息去掉) -->

```

**Comment by eycorsican** [comment]
等会发个版本做兼容处理
