### ISSUE TITLE
希望有一个方便查看流量或DNS是否走代理及其目标网址、发起APP等信息的功能

### ISSUE THREAD

**Issue by wenjinlibug** [eycorsican/kitsunebi-android#43]
### 你正在使用哪个版本？
kitsunebi-android版本：1.4.5

### 使用最新版本是否还遇到同样的问题？
是

### 你的手机型号和手机操作系统版本是多少？
手机型号：小米9
操作系统版本：MIUI10.2 稳定版未解锁

### 你遇到了什么问题？
因需要调整配置文件内路由及DNS代理设置、需要查阅log，
但log完全没有过滤功能，同时log中充斥着很多不知功能的连接。
当然导出到电脑是可以简单解决问题、然而这就不算是软件本身的易用性。
另一方面因为都是手机上使用各种app后才临时发现代理中路由设置的问题，
因此需要一个能以浮动窗口简略显示当前APP流量及DNS是否经代理的界面，
另外需要更详细的log（发起的APP，目的地网址，是否握手成功等）及过滤功能方便排查。

**Comment by eycorsican** [comment]
连接统计 功能应该已经满足你的需要，你可以在 PC 上打开那个网址看。
