### ISSUE TITLE
ss订阅出错，更新订阅之后端口号和备注不能正确填入

### ISSUE THREAD

**Issue by ZevAlain** [eycorsican/kitsunebi-android#48]
### 你正在使用哪个版本？
1.4.5

### 使用最新版本是否还遇到同样的问题？
应该是最新版，google play中下载。

### 你的手机型号和手机操作系统版本是多少？
oneplus 5 : Android 9.1

### 你遇到了什么问题？
ss订阅出错，更新订阅之后端口号和备注不能正确填入

### 你正使用的配置

conf文件内容如下：
ss://
(密码和加密方式的base64加密)
@
(服务器IP)
:
(端口号)
/?#
(备注)

以上是一行内容，更新规则之后端口号显示是null，备注为空。如果可以的看一下我的问题，万分感谢。

**Comment by eycorsican** [comment]
SS的话建议使用它官方的规范来写，就是去掉路径和问号。这个东西没办法，很不好同时兼容。

**Comment by iGGrk** [comment]
似乎vmess后跟着ss，会部分报错，只显示ss

ss://YWVzLTI1Ni1nY206MEAwLjAuMC4wOjE=#中文
{"add":"server","port":"1","id":"id","net":"tcp","ps":"中文","host":"","path":"","tls":"","aid":"0","type":"none","v":"2"}

以上base64
ss那段解码aes-256-gcm:0@0.0.0.0:1

**Comment by eycorsican** [comment]
写法不对，每行都需要是个URI， vmess://... 或 ss://...
