### ISSUE TITLE
Can't add Shadowsocks server with salsa20 encryption method

### ISSUE THREAD

**Issue by yshalsager** [eycorsican/kitsunebi-android#58]
### 你正在使用哪个版本？
1.5.6

### 使用最新版本是否还遇到同样的问题？
Yes

### 你的手机型号和手机操作系统版本是多少？
Xiaomi Note 5 - Android 9.0 

### 你遇到了什么问题？
I can't add a shadowsocks server which use salsa20 as encryption method. 

### 你遇到的问题可以用固定步骤重现吗？
Yes, try adding any ss:// URI, it'll be added but it won't be able to connect.

**Comment by eycorsican** [comment]
won't fix
