### ISSUE TITLE
仅建议，对比当前 BifrostV 的功能增加请求

### ISSUE THREAD

**Issue by NewBugger** [eycorsican/kitsunebi-android#59]
1. 从文件导入配置
2. 为配置文件单独设置分应用代理
3. 状态栏提醒显示当前配置名称
4. 点击状态栏提醒，进入应用内
5. 状态栏提醒中显示上传下载速率
6. 卡片任务的 kitsunebi 颜色还是默认的蓝色，希望能适配主题切换后的粉红
7. proxy logs 显示发出请求的应用名（和图标）

致谢。

**Comment by ghost** [comment]
同建议，希望可以加上
1. 手动调整配置文件顺序
2. 订阅节点可以选择展开或收起(类似SSD)
3. logcat减少ui方面的日志
4. 订阅模式改为完全清除节点，重新订阅的模式
5. 传输层配置选择ws时可以自定义header
6. 可以全局调整mux的开启和关闭

谢谢
