### ISSUE TITLE
最新版本断流严重

### ISSUE THREAD

**Issue by sbily1988** [eycorsican/kitsunebi-android#6]
最新版本，按readme里面日用模板增加了自用的ws+TLS+CDN  outbound断流严重，

**Comment by eycorsican** [comment]
可以描述一下“断流“具体是什么表现吗？有条件的话能够附上用 adb 获取的相关日志吗？

**Comment by sbily1988** [comment]
就是我正看着YouTube呢，突然就不缓冲了，这时候我切出去发现浏览器也无法访问Google了，telegram也陷入了一直连接网络的状态，然后我把kitsunebi从后台清除再打开就又可以用了，这样的现象会随机出现

**Comment by eycorsican** [comment]
你说的 “从后台清除再打开” 操作似乎只针对 UI APP？这个过程中，有对VPN进行断开再链接吗？

**Comment by sbily1988** [comment]
我完全清除后台的时候，kitsunebi就彻底退出了，VPN也会断开，你说得adb获取日志是指   adb logcat 一下吗？

**Comment by eycorsican** [comment]
你具体是怎么“后台清除APP”的？不是按下方最右按钮调出APP列表然后划掉吗？如果是这样的话清楚后VPN连接是不会断开的

是的，就是指 logcat 的日志，最好把 v2ray 日志等级设为 debug

**Comment by sbily1988** [comment]
我用的一加5T app 列表划掉就可以彻底清除程序,vpn那个钥匙的标志也没有了

**Comment by eycorsican** [comment]
好吧涨见识了。有一点点头绪，不太确定，下个版本会尝试修一下

**Comment by sbily1988** [comment]
[logcat.zip](https://github.com/eycorsican/kitsunebi-android/files/2716966/logcat.zip)

**Comment by sbily1988** [comment]
辛苦了,谢谢

**Comment by eycorsican** [comment]
你可以测试下 0.5.2 吗？问题还没算修复，只是想验证一下想法，这次如果要“断流”，预计 VPN 图标也会一起消失

**Comment by sbily1988** [comment]
好的，我试试

**Comment by sbily1988** [comment]
14:57分左右
0.5.2同样出现上述情况, 而且断流的时候VPN图标并没有消失,
新发现:断流时候,,,国内网络也无法链接,比如微信无法登录,百度无法访问
![3](https://user-images.githubusercontent.com/22991766/50545146-1bc9d680-0c45-11e9-8905-a34e3d998f8f.jpg)
![2](https://user-images.githubusercontent.com/22991766/50545147-1bc9d680-0c45-11e9-9f5c-024592c77074.jpg)
![webwxgetmsgimg](https://user-images.githubusercontent.com/22991766/50545148-1bc9d680-0c45-11e9-896e-b7cd518e6ffe.jpg)
[logcat.zip](https://github.com/eycorsican/kitsunebi-android/files/2716991/logcat.zip)

**Comment by eycorsican** [comment]
你可以把日志等级调为 debug 吗？不然很多信息没办法看到。
```json
    "log": {
        "loglevel": "debug"
    }
```

**Comment by sbily1988** [comment]
[logcat.zip](https://github.com/eycorsican/kitsunebi-android/files/2717081/logcat.zip)
连续看youtube40分钟后约19:08复现

**Comment by sbily1988** [comment]
好的

**Comment by eycorsican** [comment]
0.5.4 又修了下

**Comment by sbily1988** [comment]
辛苦了

**Comment by sbily1988** [comment]
棒极了，0.5.4到目前为止没有再出现 “断流”  了

**Comment by eycorsican** [comment]
可以也测一下下 0.5.5 吗？我改了另一种修复方式

**Comment by sbily1988** [comment]
你好，0.5.5今天一天也没有断流的现象了，谢谢
