### ISSUE TITLE
扫码功能闪退/申请机场订阅格式适配

### ISSUE THREAD

**Issue by Anoneko** [eycorsican/kitsunebi-android#61]
### 你正在使用哪个版本？
1.5.6

### 使用最新版本是否还遇到同样的问题？
是

### 你的手机型号和手机操作系统版本是多少？
HUAWEI HMA-AL00 | 9.1.0.120(C00E119R1P21)

### 你遇到了什么问题？
使用扫码添加节点功能会闪退，订阅功能不支持sspanel-v3-mod-Uim所生成的格式，仅能添加订阅列表中的首个节点

### 你遇到的问题可以用固定步骤重现吗？
可以

**Comment by eycorsican** [comment]
我需要一个样例

**Comment by iGGrk** [comment]
{"add":"%s","port":"%s","id":"%s","net":"kcp","ps":"%s","host":"","path":"","tls":"", "aid":"0","type":"utp","v":"2"}
