### ISSUE TITLE
App crashes when tapping the connect button on KitKat

### ISSUE THREAD

**Issue by skygate2012** [eycorsican/kitsunebi-android#62]
Does this app support KitKat devices? Any config would result in immediate crash after pressing the connect button. The app is tested OK on my newer device running Android 9.

**Comment by eycorsican** [comment]
The app should support Android 4.2 and above, please upload the crash log.

**Comment by skygate2012** [comment]
Where can I find the crash log? Logcat is empty.
![Screenshot_2019-06-11-08-03-53](https://user-images.githubusercontent.com/7148976/59234838-14115380-8c21-11e9-8cea-80f794d7beb2.png)

**Comment by skygate2012** [comment]
It turns out that there was a `69removelogger` file present in `/system/etc/init.d`, logcat is available now after commenting the line that removes log files.
[logcat_08-27-2019_07-44-10.txt](https://github.com/eycorsican/kitsunebi-android/files/3543610/logcat_08-27-2019_07-44-10.txt)

**Comment by eycorsican** [comment]
Please try 1.7.1.

**Comment by skygate2012** [comment]
[logcat_09-01-2019_07-20-06.txt](https://github.com/eycorsican/kitsunebi-android/files/3562923/logcat_09-01-2019_07-20-06.txt)
Updated but issue remains the same.

**Comment by skygate2012** [comment]
It seems that the author has beat the devil out of this issue as of 1.7.2, thank you for your efforts! @eycorsican 
![screenshot](https://user-images.githubusercontent.com/7148976/65611701-c65d0300-dfe5-11e9-8b90-f1af3a1a6220.jpg)
