### ISSUE TITLE
分应用代理bug 

### ISSUE THREAD

**Issue by zack66** [eycorsican/kitsunebi-android#63]
### 你正在使用哪个版本？
1.6.1

### 使用最新版本是否还遇到同样的问题？
上个版本不会 刚刚play商店更新后出现的

### 你的手机型号和手机操作系统版本是多少？
OnePlus 5T Android 9.0

### 你遇到了什么问题？
分应用代理Bug

### 你遇到的问题可以用固定步骤重现吗？
打开分应用代理 选择允许列表 选中需要代理的应用 保存
返回主界面 选中配置连接
然后查看分应用代理列表刚刚选中保存的应用全部变为未选中状态

**Comment by zack66** [comment]
还有个问题就是每次点连接过一小会才能科学上网 其他的代理客户端如ClashA V2RayNG点连接都可以立即科学上网是为什么？

**Comment by zack66** [comment]
还有是否会增加SSR代理？

**Comment by chocolatesir** [comment]
安卓8.0我这边刚刚也复现了，更新后分应用里允许通过的app全部没有被选中，设置好保存后再次打开后又会消失，并且分应用里只有导出，没有导入。

**Comment by zack66** [comment]
> 安卓8.0我这边刚刚也复现了，更新后分应用里允许通过的应用全部没有被选中，设置好保存后再次打开后又会消失，并且分应用里只有导出，没有导入。

看了更新日志 目前解决方法得配置规则集

**Comment by zack66** [comment]
建议还是在分应用代理列表中添加导入按钮而不是配置在规则集中

**Comment by chocolatesir** [comment]
在规则集后面添加了分应用后正常了，但是我的规则集是添加的https://raw.githubusercontent.com/ConnersHua/Profiles/self-use/Kitsunebi/Routing.conf第三方规则，一点更新分应用规则就会被覆盖掉。

**Comment by eycorsican** [comment]
应该已经在1.6.2中修复
