### ISSUE TITLE
自定义配置是否会更新？

### ISSUE THREAD

**Issue by Azureki** [eycorsican/kitsunebi-android#66]
就是v2ray的json格式的配置。不是规则集/订阅。

我自己写了规则，上传到网站，然后在kitsunebi中`从url导入配置`。
但是似乎没有更新的方式？会自动更新吗？

**Comment by lanceliao** [comment]
Kitsunebi的自定义配置不会自动更新，你需要重新手动导入一次

**Comment by Azureki** [comment]
了解，谢谢解答

**Comment by Azureki** [comment]
了解，谢谢解答
