### ISSUE TITLE
请升级支持TLS 1.3以改善速度、响应度和安全度

### ISSUE THREAD

**Issue by moralrebuild** [eycorsican/kitsunebi-android#68]
### 你正在使用哪个版本？
1.6.6

### 使用最新版本是否还遇到同样的问题？
是

### 你的手机型号和手机操作系统版本是多少？
Nexus 6P 谷歌 原厂 Android 8.1.0

### 你遇到了什么问题？
速度与Windows 10上的相比慢了5倍以上。用speedtest测试，使用speedtest的相同服务器

### 你遇到的问题可以用固定步骤重现吗？
TLS+WS 模式

使用Caddy为服务器前端，配置：
abc.com {
root /var/www/html
tls www@abc.com
proxy /ray localhost:10000 {
    websocket
    header_upstream -Origin
  }
}

**Comment by lanceliao** [comment]
4.19.1及以上的版本的v2ray-core已经支持TLS v1.3了，Kitsunebi 1.6.8可以支持

**Comment by moralrebuild** [comment]
@lanceliao 谢谢，但我看到谷歌应用商店的版本依然是1.6.6
