### ISSUE TITLE
希望你开发linux版，linux终端wget没代理可用😭

### ISSUE THREAD

**Issue by zz1616611** [eycorsican/kitsunebi-android#70]
希望使用socks直接代理wget
linux那么大，竟然没一个简单好用的终端代理。

**Comment by jvedi** [comment]
Polipo , Privoxy , Squid 这么多经典，竟然说没有... ，Linux上只会比windows更灵活更好。

如果说是傻瓜式操作，点点按钮就完事的，请忽略我上面说的~~~虽然也不复杂 :)

**Comment by wangxunqi** [comment]
在 Linux 中使用以下环境变量即可在当前 session 使用全局 HTTP 代理（很多软件都支持这一设置，也有不支持的）。
```
export http_proxy=http://127.0.0.1:8080/ (地址须改成你配置的 HTTP 入站代理地址)
export https_proxy=$http_proxy
```

**Comment by s-kk** [comment]
@zz1616611
Proxychains

**Comment by Samcall** [comment]
百度贴吧的怎么来这儿了。

**Comment by lxl6125** [comment]
也许你需要这个？
https://github.com/lhy0403/Qv2ray
