### ISSUE TITLE
分应用代理有问题

### ISSUE THREAD

**Issue by ssacpklnm** [eycorsican/kitsunebi-android#72]
### 你正在使用哪个版本？
1.6.13

### 使用最新版本是否还遇到同样的问题？

有
### 你的手机型号和手机操作系统版本是多少？
1+7pro 9.0

### 你遇到了什么问题？

分应用代理无效，无论启用允许还是不允许列表，就是不起作用，允许列表里只选了chrome，play依旧能用，或者不允许列表里选taptap，进去之后依旧是国际版
### 你正使用的配置
```json

<!-- 请把你的配置文件复制至此 (建议把服务器和用户信息去掉) -->

```

**Comment by Samcall** [comment]
1.7.0试了一下果然不起作用。需要断开重连才生效。
