### ISSUE TITLE
ss+ws模式无法连接

### ISSUE THREAD

**Issue by skyfly0** [eycorsican/kitsunebi-android#74]
### 你正在使用哪个版本？
1.6.13

### 使用最新版本是否还遇到同样的问题？
是

### 你的手机型号和手机操作系统版本是多少？
荣耀V20，安卓9

### 你遇到了什么问题？
ss+ws模式无法连接，使用ss安卓版+v2ray-plugin可以正常连接。观察调试分析离得运行配置那边，看到正常情况下应该是"path":"/“的那行变成了"path":"\\\/"，不清楚和这个有没有关系。

**Comment by ghost** [comment]
这个是你自己配置的问题，不是kit的问题，配置文件的格式，vmess+ws=ss+ws≠ss+v2ray-plugin
