### ISSUE TITLE
请求添加“删除所有节点并重新订阅”功能

### ISSUE THREAD

**Issue by LanbenGG** [eycorsican/kitsunebi-android#89]
### 你正在使用哪个版本？
1.7.0

### 使用最新版本是否还遇到同样的问题？
是

### 你的手机型号和手机操作系统版本是多少？
华为荣耀V8 KNT-AL20
Android 8.0.0/EMUI 8.0.0
### 你遇到了什么问题？
每次更新节点信息后，都必须删除所有节点再重新订阅，当节点很多的情况下，这个操作费时费力。另外，当其中一个节点的服务信息改变后，更新订阅后却不会更改之前已经添加的节点信息。

### 你遇到的问题可以用固定步骤重现吗？
可以

**Comment by eycorsican** [comment]
你可以删除订阅，订阅的节点也会被同时删除，然后再重新加一下订阅
